board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index),
    path('list/', views.list, name='list'),
    path('view/<int:bid>/', views.view),
    path('write/', views.write, name='write'),
    path('update/<int:bid>/', views.update),
    path('delete/<int:bid>/', views.delete)
]

config/urls.py
from django.contrib import admin
from django.urls import path

from board import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('board/', views.index),
    path('board/', include('board.urls')),
    path('rest/', include('rest.urls'))

]

rest/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('boards/', views.BoardListView.as_view()),
    path('boards/create/', views.BoardCreateView.as_view()),
    path('boards/<pk>/', views.BoardDetailView.as_view()),
    path('employees/', views.EmployeeListView.as_view())

]

board/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Board(models.Model):
    # id = models.IntegerField() #자동생성이므로 생략 가능
    title = models.CharField(max_length=100)
    userid = models.CharField(max_length=18)
    regdate = models.DateTimeField(default=timezone.localtime)
    views = models.IntegerField(default=0)
    thumbup = models.IntegerField(default=0)
    contents = models.TextField()

class Employee(models.Model):
    fname = models.CharField(max_length=20)
    lname = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    hdate = models.DateField()
    jobid = models.CharField(max_length=20)
    sal = models.IntegerField()
    commpct = models.FloatField()
    mgrid = models.IntegerField()
    deptid = models.IntegerField()

rest/models.py
from django.db import models

# Create your models here.

board/forms.py
from django.forms import ModelForm
from board.models import Board


class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'userid', 'contents']

board/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from board.forms import BoardForm
from board.models import Board

# Create your views here.


def index(request):
    return render(request, 'index.html')

# def list(request):
#     return render(request, 'board/list.html')

def list(request):
    bdlist = Board.objects.values('id', 'title', 'userid', 'regdate', 'views', 'thumbup')
    bdlist = bdlist.order_by('-regdate')
    bds = {'bds':bdlist}
    return render(request, 'board/list.html', bds)

def view(request, bid):
    board = Board.objects.get(id=bid)
    board.views = board.views + 1
    board.save()

    bd = {'bd': board}
    return render(request, 'board/view.html', bd)


def write(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/board/list')
    else:
        form = BoardForm()
    return render(request, 'board/write.html', {'form':form})

def update(request, bid):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            bd = Board.objects.get(id=bid)
            bd.title = form.cleaned_data['title']
            bd.contents = form.cleaned_data['contents']

            bd.save()
            return redirect('/board/list')
    else:
        board = Board.objects.get(id=bid)
        bd = {'bd':board}

    return render(request, 'board/update.html', bd)
    # board = Board.objects.get(id=bid)
    # bd = {'bd' : board }
    # return render(request, 'board/update.html', bd)

def delete(request, bid):
    bd = Board.objects.get(id=bid)
    bd.delete()

    return redirect('/board/list') #page 전환하는 명령어 redirect

rest/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework.generics import ListAPIView, RetrieveAPIView, RetrieveUpdateDestroyAPIView, CreateAPIView
from board.models import Board, Employee
from rest.serializers import BoardSerializer, BoardDetailSerializer, BoardCreateSerializer, EmployeeSerializer, EmployeeDetailSerializer


class BoardListView(ListAPIView):
    queryset = Board.objects.all()
    serializer_class = BoardSerializer


# class BoardDetailView(RetrieveAPIView):
class BoardDetailView(RetrieveUpdateDestroyAPIView):
    queryset = Board.objects.all()
    serializer_class = BoardDetailSerializer


class BoardCreateView(CreateAPIView):
    queryset = Board.objects.all()
    serializer_class = BoardCreateSerializer

class EmployeeListView(ListAPIView):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

class EmployeeDetailView(RetrieveUpdateDestroyAPIView):
    queryset = Employee.objects.all()
    serializer_class = EmployeeDetailSerializer

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bs4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fa47/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/semiproject.css' %}">
    <title>부트스트랩4-index</title>
</head>
<body>
<div class="container">
    <header><!-- 상단로고/로그인,회원가입버튼 -->
        <div class="row">
            <div class="col-md-6">
                <h1><a href="/board/">Lorem Ipsum</a></h1>
            </div>
            <div class="col-md-6 text-right">
                <h1><button type="button"
                    class="btn btn-danger"
                    data-toggle="modal"
                    data-target="#loginmodal">로그인</button>
                <button type="button"
                    class="btn btn-primary"
                        id="joinbtn">회원가입</button></h1>
            </div>
        </div>
    </header>
    <nav class="nav navbar-expand-md navbar-dark bg-dark">
        <ul class="nav navbar-nav nav-fill w-100">
            <li class="nav-item"><a class="nav-link" href="">프로젝트소개</a></li>
            <li class="nav-item"><a class="nav-link" href="">회원가입</a></li>
            <li class="nav-item"><a class="nav-link" href="/board/list">게시판</a></li>
            <li class="nav-item"><a class="nav-link" href="">자료실</a></li>
            <li class="nav-item"><a class="nav-link" href="">갤러리</a></li>
            <li class="nav-item"><a class="nav-link" href="">관리자</a></li>
        </ul>
    </nav>

<!-- 메인영역 시작 -->
{% block content %}
    {% endblock %}

<!-- 메인영역 끝 -->


    <footer>
        <h6 class="bg-light text-right">Copyright &copy; Lorem Ipsum 2020.
            All right Reserved. Created by Bootstrap4.</h6>
    </footer>
</div>

<!-- 로그인 모달 시작 -->
<div id="loginmodal" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">로그인</h3>
                <button class="btn btn-light" type="button"
                        data-dismiss="modal">닫기</button>
            </div>
            <div class="modal-body">
                <form id="loginfrm">
                    <div class="form-group row text-center">
                        <label for="uid"
                               class="col-form-label col-4">아이디</label>
                        <input type="text" id="uid"
                               class="form-control col-6">
                    </div>
                    <div class="form-group row text-center">
                        <label for="pwd"
                                class="col-form-label col-4">비밀번호</label>
                        <input type="password" id="pwd"
                                class="form-control col-6">
                    </div>
                    <div class="form-group row text-center">
                        <div class="col-4"></div>
                        <div class="form-check">
                            <input type="checkbox"
                                   class="form-check-input">
                            <label class="form-check-label">
                                로그인 상태 유지</label>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer justify-content-center">
                <button type="button"
                        class="btn btn-danger">로그인</button>
                <button type="button"
                        class="btn btn-success">아이디/비밀번호 찾기</button>
            </div>
        </div>
    </div>
</div>
<!-- 로그인 모달 끝 -->

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="{% static 'bs4/js/bootstrap.min.js'%}"></script>
<script>function areyoudelete(bid) {if (confirm('정말로 삭제?')) {location.href='/board/delete/'+bid;}}</script>
</body>
</html>

templates/board/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- 메인영역 시작 -->
<div id="main">
    <div class="margin30">
        <i class="fa fa-comments fa-2x"> 자유게시판</i>
        <hr>
    </div> <!-- 타이틀 -->

    <div class="row margin1050">
        <div class="col-12 text-right">
            <a href="{% url 'board:write' %}" id="newbd"
                    class="btn btn-light">
                <i class="fa fa-plus-circle"> </i>
                새글쓰기
            </a>
        </div>
    </div><!-- 버튼들 -->

    <div class="row margin1050">
        <div class="col-12">
            <table class="table table-striped"
                style="border-bottom: 3px solid black;
                       border-top: 3px solid black">
                <thead style="background: #dff0d8">
                    <tr><th style="width: 7%">번호</th>
                        <th>제목</th>
                        <th style="width: 12%">작성자</th>
                        <th style="width: 10%">작성일</th>
                        <th style="width: 7%">추천</th>
                        <th style="width: 7%">조회</th></tr>
                </thead>
                <tbody>
                    <tr><th>공지</th>
                        <th><span class="badge badge-danger">Hot</span>
                        '다크나이트 라이지즈' 예매권 증정이벤트 실시!!</th>
                        <th>운영자</th>
                        <th>2012.07.15</th>
                        <th>10</th>
                        <th>128</th></tr>

<!--                    <c:forEach var="b" items="${bdlist}">-->
                    {% for b in bds %}
                        <tr><td>{{b.id}}</td>
                        <td><a href="/board/view/{{b.id}}">
                                            {{b.title}}</a></td>
                        <td>{{b.userid}}</td>
                        <td>{{b.regdate|date:'Y-m-d'}}</td>
                        <td>{{b.views}}</td>
                        <td>{{b.thumbup}}</td></tr>
                    {% endfor %}
<!--                    </c:forEach>-->

                </tbody>
            </table>
        </div>
    </div><!-- 게시판 목록 -->

    <div class="row margin1050">
        <div class="col-12">
            <nav>
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a href="#" class="page-link">이전</a></li>
                    <li class="page-item active">
                        <a href="#" class="page-link">1</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">2</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">3</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">4</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">5</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">6</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">7</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">8</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">9</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">10</a></li>
                    <li class="page-item ">
                        <a href="#" class="page-link">다음</a></li>
                </ul>
            </nav>
        </div>
    </div><!-- 페이지 네비게이션 -->

</div>
<!-- 메인영역 끝 -->
{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- 메인영역 시작 -->

<div id="main">
    <div class="margin30">
        <i class="fa fa-comments fa-2x"> 자유게시판</i>
        <hr>
    </div> <!-- 타이틀 -->

    <div class="row margin1050">
        <div class="col-6">
           <h4><i class="fa fa-pencil-square-o"></i>
               수정하기</h4>
        </div>
        <div class="col-6 text-right">
            <button type="button" id="lstbd"
                    class="btn btn-light">
                <i class="fa fa-list"> </i>
                목록으로
            </button>
        </div>
    </div><!-- 버튼들 -->

    <div class="row mgnpdg15">
        <form class="card card-body bg-light"  method = "post", name ="updfrm">
            {% csrf_token %}

            <div class="form-group row">
                <label class="col-form-label col-2 text-right">
                    제목</label>
                <input type="text" id="title" name="title"
                       class="form-control col-9"
                    value="{{bd.title}}">
            </div><!-- 제목 -->

            <div class="form-group row">
                <label class="col-form-label col-2 text-right">
                    작성자</label>
                <input type="text" id="userid" name="userid"
                     class="form-control col-9" readonly value="{{bd.userid}}">
            </div><!-- 작성자 -->

            <div class="form-group row">
                <label class="col-form-label col-2 text-right">
                    본문내용</label>
                <textarea id="contents" name="contents" rows="15"
                     class="form-control col-9">{{bd.contents}}</textarea>
            </div><!-- 본문내용 -->

            <div class="form-group row">
                <label class="col-form-label col-2 text-right">
                    자동가입방지</label>
                <img src="{% static '/img/google_recaptcha.gif'%}"
                     width="50%" height="50%"
                     style="margin-left: -5px">
            </div><!-- 자동가입방지 -->

            <div class="row justify-content-center"
                style="margin-top: 55px">
                <hr style="width:90%; color:grey; margin: 35px 0">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-pencil-square-o"></i>수정하기
                </button>&nbsp;
                <a href ="{% url 'board:list' %}" class="btn btn-danger">
                    <i class="fa fa-remove"></i>취소하기
                </a>
            </div><!-- 버튼들 -->

        </form>
    </div><!-- 새글쓰기 폼 -->
</div>
 
<!-- 메인영역 끝 -->
{% endblock %}

templates/board/view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- 메인영역 시작 -->

<div id="main">
        <div class="margin30">
            <i class="fa fa-comments fa-2x"> 자유게시판</i>
            <hr>
        </div> <!-- 타이틀 -->

        <div class="row margin1050">
            <div class="col-6">
                <button type="button" id="prevbd"
                        class="btn btn-light"
                        style="margin-left: -14px">
                    <i class="fa fa-chevron-left"> </i>
                    이전게시물
                </button>
                <button type="button" id="nextbd"
                        class="btn btn-light">
                    <i class="fa fa-chevron-right"> </i>
                    다음게시물
                </button>
            </div>
            <div class="col-6 text-right">
                <a href="{% url 'board:write' %}" id="newbd"
                        class="btn btn-light"
                        style="margin-right: -14px">
                    <i class="fa fa-plus-circle"> </i>
                    새글쓰기
                </a>
            </div>
        </div><!-- 버튼들 -->

        <div class="row margin1050">
            <table class="table">
                <tr><th colspan="2"
                    style="border-bottom: 3px solid black;
                           background: #dff0f8">
                    <h3>{{bd.title}}</h3>
                </th></tr>
                <tr style="background: #ccff99">
                    <td class="text-left">{{bd.userid}}</td>
                    <td class="text-right">{{bd.regdate|date:'Y-m-d h:i:s'}} / {{bd.views}} / {{bd.thumbup}}</td></tr>
                <tr style="background: #ffffcc">
                    <td colspan="2" class="text-left"
                        style="border-bottom: 3px solid black;">{{bd.contents}}</td></tr>
            </table>
        </div><!-- 본문 -->

        <div class="row margin1050">
            <div class="col-6">
                <a href="/board/update/{{bd.id}}"  id="updbd"
                        class="btn btn-warning"
                        style="margin-left: -14px">
                    <i class="fa fa-pencil"> </i>
                    수정하기
                </a>

                <button type='button' id="delbd"
                        class="btn btn-danger"
                        onclick="areyoudelete('{{bd.id}}')">
                    <i class="fa fa-trash-o"> </i>
                    삭제하기
                </button>
            </div>
            <div class="col-6 text-right">
                <a href="{% url 'board:list' %}" id="lstbd"
                        class="btn btn-light"
                        style="margin-right: -14px">
                    <i class="fa fa-list"> </i>
                    목록으로
                </a>
            </div>
        </div><!-- 버튼들 -->

        <div class="row margin1050">
            <h3 style="margin-top: 45px"><i class="fa fa-commenting"></i> 나도 한마디</h3>
            <table class="table" style="border-top: 3px solid black;
                                        border-bottom:3px solid black">
                <tr><td style="width:25%" class="text-left"><h4>zzyigy</h4></td>
                    <td>
                        <div style="background: yellow; padding: 5px 0">2012-02-08 14:43:49</div>
                        <p style="padding: 5px 0">지금도 등골 브레이커 맞습니다.<br>
                            애들 레고교육센터인가 뭔가 보낼려다가...학원비는 둘째치고, <br>
                           재료비에서 깜놀...<br><br>
                            그냥 작은 거 사다가 애들하고 맞추고 놀고 있습죠 ^^</p>
                        <ul class="list-unstyled"><!-- 댓글의 댓글 시작 -->
                            <li>
                                <div style="background: lime; padding: 5px 0">
                                    <span><b>zzyzzy</b></span>
                                    <span style="float: right">2012-02-08 14:50:35</span></div>
                                <p style="padding: 5px 0">정말인가요? 우아~ 심하다!~</p>
                            </li>
                        </ul>
                    </td></tr>

                <tr><td style="width:25%" class="text-left"><h4>zzyigy</h4></td>
                    <td>
                        <div style="background: yellow; padding: 5px 0">2012-02-08 14:43:49</div>
                        <p style="padding: 5px 0">지금도 등골 브레이커 맞습니다.<br>
                            애들 레고교육센터인가 뭔가 보낼려다가...학원비는 둘째치고, <br>
                            재료비에서 깜놀...<br><br>
                            그냥 작은 거 사다가 애들하고 맞추고 놀고 있습죠 ^^</p>
                    </td></tr>

                <tr><td style="width:25%" class="text-left"><h4>zzyigy</h4></td>
                    <td>
                        <div style="background: yellow; padding: 5px 0">2012-02-08 14:43:49</div>
                        <p style="padding: 5px 0">지금도 등골 브레이커 맞습니다.<br>
                            애들 레고교육센터인가 뭔가 보낼려다가...학원비는 둘째치고, <br>
                            재료비에서 깜놀...<br><br>
                            그냥 작은 거 사다가 애들하고 맞추고 놀고 있습죠 ^^</p>
                    </td></tr>

                <tr><td style="width:25%" class="text-left"><h4>zzyigy</h4></td>
                    <td>
                        <div style="background: yellow; padding: 5px 0">2012-02-08 14:43:49</div>
                        <p style="padding: 5px 0">지금도 등골 브레이커 맞습니다.<br>
                            애들 레고교육센터인가 뭔가 보낼려다가...학원비는 둘째치고, <br>
                            재료비에서 깜놀...<br><br>
                            그냥 작은 거 사다가 애들하고 맞추고 놀고 있습죠 ^^</p>
                    </td></tr>

                <tr><td style="width:25%" class="text-left"><h4>zzyigy</h4></td>
                    <td>
                        <div style="background: yellow; padding: 5px 0">2012-02-08 14:43:49</div>
                        <p style="padding: 5px 0">지금도 등골 브레이커 맞습니다.<br>
                            애들 레고교육센터인가 뭔가 보낼려다가...학원비는 둘째치고, <br>
                            재료비에서 깜놀...<br><br>
                            그냥 작은 거 사다가 애들하고 맞추고 놀고 있습죠 ^^</p>
                    </td></tr>


            </table>
        </div><!-- 댓글 -->

        <div class="row margin1050">
            <form class="card card-body bg-light"
                style="margin: 30px 0;">
                <div class="form-group row">
                    <label style="margin:auto">로그인하세요</label>

                    <textarea id="comment" rows="10"
                        class="form-control col-7"></textarea>

                    <button type="button" id="bdcmt"
                        class="btn btn-dark" style="margin:auto">
                        <i class="fa fa-commenting"></i>
                        댓글쓰기</button>
                </div>
            </form>
        </div><!-- 댓글쓰기 -->

    </div>

<!-- 메인영역 끝 -->
{% endblock %}

templates/board/write.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- 메인영역 시작 -->

	<div id="main">
        <div class="margin30">
            <i class="fa fa-comments fa-2x"> 자유게시판</i>
            <hr>
        </div> <!-- 타이틀 -->

        <div class="row margin1050">
            <div class="col-6">
               <h4><i class="fa fa-plus-circle"></i>
                   새글쓰기</h4>
            </div>
            <div class="col-6 text-right">
                <a href="{% url 'board:list' %}" id="lstbd"
                        class="btn btn-light">
                    <i class="fa fa-list"> </i>
                    목록으로
                </button>
            </div>
        </div><!-- 버튼들 -->

        <div class="row mgnpdg15">
            <form class="card card-body bg-light"
                  name="bdfrm" id="bdfrm" method="post">
                {% csrf_token %}

                <!-- 오류표시 Start -->
                {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                    </div>
                {% endif %}
                <!-- 오류표시 End -->
                <div class="form-group row">
                    <label class="col-form-label col-2 text-right">
                        제목</label>
                    <input type="text" id="title" name="title"
                           class="form-control col-9"
                    value="{{form.title.value|default_if_none:''}}">

                </div><!-- 제목 -->

                <div class="form-group row">
                    <label class="col-form-label col-2 text-right">
                        작성자</label>
                    <input type="text" id="userid" name="userid"
                         class="form-control col-9"
                         value="{{form.title.value|default_if_none:''}}">
                </div><!-- 작성자 -->

                <div class="form-group row">
                    <label class="col-form-label col-2 text-right">
                        본문내용</label>
                    <textarea id="contents" name="contents" rows="15" # textarea text보다 더 많은 양의 텍스트를 닮을 수 있음
                         class="form-control col-9">
                        {{form.contents.value|default_if_none:''}}</textarea>
                </div><!-- 본문내용 -->

                <div class="form-group row">
                    <label class="col-form-label col-2 text-right">
                        자동가입방지</label>
                    <img src="{% static 'img/google_recaptcha.gif' %}"
                         width="50%" height="50%"
                         style="margin-left: -5px">
                </div><!-- 자동가입방지 -->

                <div class="row justify-content-center"
                    style="margin-top: 55px">
                    <hr style="width:90%; color:grey; margin: 35px 0">
                    <button type="submit" id="bdregbtn"
                            class="btn btn-primary">
                        <i class="fa fa-check"></i>입력하기
                    </button>&nbsp;
                    <button type="reset" id="bdnobtn"
                            class="btn btn-danger">
                        <i class="fa fa-remove"></i>취소하기
                    </button>
                </div><!-- 버튼들 -->

            </form>
        </div><!-- 새글쓰기 폼 -->
    </div>
 
<!-- 메인영역 끝 -->
{% endblock %}